### ISSUE TITLE
How to build a local version of a package?

### ISSUE THREAD

**Issue by alexherbo2** [nix-community/nixpkgs-wayland#196]
When Nixpkgs already provides the package for a project I’m working on, I can use `nix-shell '<nixpkgs>' --attr <package>` to test my changes, but it does not work with overlays.

My use case is to compile a local version of [Wayfire].

[Wayfire]: https://wayfire.org

**Comment by colemickens** [comment]
@alexherbo2 Unfortunately this is an aspect of overlays I find a bit annoying myself. I just try to keep an eye on my overlays I have configured for my user (`~/.config/nixpkgs/overlays`). If you add this overlay there, it will apply over your nixpkgs.

However, that's messy and mutates your <nixpkgs> everywhere which can lead to really surprising results if you forget.

So, you can do something like this in a `shell.nix` instead: https://github.com/colemickens/nixcfg/blob/master/shells/uber-devenv.nix#L5

Sorry for the late reply. GitHub eats a lot of notification emails these days. :(

**Comment by Artturin** [comment]
`nix build ".#wayfire"`
