### ISSUE TITLE
add flake support

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#216]
I'm adding it for my system config. I'm not sure if flakes adds a ton of value for an overlay since it doesn't really follow a nixpkgs, but I guess we shall see.

Maybe with flakes I should prefer to ship a package set that follows a flake-override-able nixpkgs?

**Comment by bqv** [comment]
I think the most productive model is providing a nixpkgs revision that you've tested and works, so that if people override that it's at their own risk.

That requires a test suite though...
