### ISSUE TITLE
Announce: redshift-wayland will be replaced by gammastep (a redshift fork)

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#224]
See: https://github.com/jonls/redshift/pull/663#issuecomment-660526594

Maybe I'll see if I can leave `redshift-wayland` as an alias and add a warning.

The `home-manager` module lets you override the package, so the existing redshift module should continue working, presumably.

**Comment by CameronNemo** [comment]
Note that the configuration path has changed from `~/.config/redshift/redshift.conf` to `~/.config/gammastep/config.ini`.
