### ISSUE TITLE
waybox: bspwc: drop

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#228]
I'm (very likely) going to drop these.

They depend on old versions of `wlroots` that no longer build on newer nixpkgs versions.

If this is a problem for you, let me know, maybe we can fix it up instead, but for now it's too much of a burden and I've been thinking of dropping these for a while anyway.

**Comment by Artturin** [comment]
6db10801e6dacfe01f959f8fe8aece52963285cb
