### ISSUE TITLE
sway: glesv2 not found

### ISSUE THREAD

**Issue by betaboon** [nix-community/nixpkgs-wayland#232]
I'm trying to build sway on an aarch64 device (raspberrypi 4) but fail to build with: 

```
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency glesv2 found: NO (tried pkgconfig)

meson.build:51:0: ERROR: Dependency "glesv2" not found, tried pkgconfig
```

I'm building against `nixos-unstable` (`30e98a4fd67c71277ee95c58c8fd691b69a09183`)

I haven't had a change to try the same on x86 yet.

Update 1: Seems like the problem does not occur on x86 

Update 2: seems like adding `libglvnd` and `mesa_noglu` to `buildInputs` results in the build finishing

**Comment by colemickens** [comment]
I can't repro this?

```
cole@slynux ~/c/nixpkgs-wayland (master)> nix build .#packages.aarch64-linux.sway-unwrapped --builders 'ssh://colemickens@aarch64.nixos.community aarch64-linux'
warning: Git tree '/home/cole/code/nixpkgs-wayland' is dirty

cole@slynux ~/c/nixpkgs-wayland (master)> ls result/bin/
sway*  swaybar*  swaymsg*  swaynag*

cole@slynux ~/c/nixpkgs-wayland (master)> file result/bin/sway
result/bin/sway: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/mj4hk2z68aqcxpl8nr0an5gspbz69gvv-glibc-2.31/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.32, not stripped

```

This builds `sway-unwrapped` from nixpkgs-wayland against `nixos-unstable`.

**Comment by colemickens** [comment]
@betaboon I had some changes that weren't pushed, maybe try again?

Here's the full build log from my Pi:

`nix build -L github:colemickens/nixpkgs-wayland#packages.aarch64-linux.sway-unwrapped`: https://gist.github.com/3881716c85b2931e60de3fb6b3950321
