### ISSUE TITLE
Package request: rofi-wayland

### ISSUE THREAD

**Issue by JamieMagee** [nix-community/nixpkgs-wayland#233]
It's already been packaged [here](https://github.com/MetaDark/nur-packages/blob/master/pkgs/applications/misc/rofi-wayland/default.nix), but I think it would still be useful to add here, as it's likely to be relevant to other users of this repo.

There's a bit of discussion in [here](https://github.com/davatorium/rofi/pull/1139), as to why it's a fork, and not being merged upstream.

**Comment by colemickens** [comment]
:+1: makes sense, I'll try to take a day or two and go through this repo issues/prs and see what I can do with some focus. And thanks for providing, albeit largely unsurprising, context.

**Comment by Jdogzz** [comment]
I think this can be closed as completed?

https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/misc/rofi/wayland.nix
