### ISSUE TITLE
package request: wlsunset

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#234]
https://sr.ht/~kennylevinsen/wlsunset/

**Comment by berbiche** [comment]
Quick question: how does wlsunset compare to gammastep?

**Comment by bnjmnt4n** [comment]
This can probably be closed, since wlsunset has landed in nixpkgs: https://github.com/NixOS/nixpkgs/blob/4a7f99d55d299453a9c2397f90b33d1120669775/pkgs/tools/wayland/wlsunset/default.nix.

**Comment by berbiche** [comment]
In that case, the wlsunset expression from nixpkgs only needs to be copied here to make it work with the auto-update bot

**Comment by bnjmnt4n** [comment]
Cool. I'll send a PR when I've got the time.

**Comment by bnjmnt4n** [comment]
Actually, it looks like there's already a package here for wlsunset, which I didn't realize: https://github.com/colemickens/nixpkgs-wayland/blob/master/pkgs/wlsunset/default.nix.
