### ISSUE TITLE
package request: nwg-panel

### ISSUE THREAD

**Issue by lemniskett** [nix-community/nixpkgs-wayland#274]
A nice addition for Sway window manager
Repo: https://github.com/nwg-piotr/nwg-panel

**Comment by berbiche** [comment]
Build information: https://github.com/nwg-piotr/nwg-panel/wiki/Installation

**Comment by berbiche** [comment]
This is now available on Nixpkgs.

If someone wants to make this available here, they can simply copy the Waybar wrapper [here[1]](https://github.com/nix-community/nixpkgs-wayland/blob/c53d6a085f24b1fc4c5d8984944317a5326311d2/pkgs/waybar/default.nix) and adapt it to nwg-panel.

1. <https://github.com/nix-community/nixpkgs-wayland/blob/c53d6a085f24b1fc4c5d8984944317a5326311d2/pkgs/waybar/default.nix>

**Comment by lemniskett** [comment]
Awesome! Thank you.

**Comment by colemickens** [comment]
I've added this to the overlay: https://github.com/nix-community/nixpkgs-wayland/commit/118dfdce8b95c5a52294c283302487382f14b444
