### ISSUE TITLE
nixos-unstable: wayland is behind

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#276]
`wlroots` wants wayland 1.19.0, but nixpkgs nixos-unstable is on 1.18.0.

I might just override it for the package, otherwise things are going to be stuck for a while. I'm not sure I have time to send this upstream either.

**Comment by colemickens** [comment]
Actually, I can't just override it here either, since it's more than just a version bump. The patch needs to be adjusted too.

So, things might just stay stuck here for a while. I'm pretty busy right now.

**Comment by fionera** [comment]
Can you pin wlroots too? Currently you cannot build it

**Comment by colemickens** [comment]
Ahh. I have an auto-update script that invoked this locally and pushed when it should't have.

I'll revert this and make sure I don't have ability to push to CI from here by default.

**Comment by colemickens** [comment]
Sorry about that @fionera, wlroots on master is buildable again. Thanks for reporting.

**Comment by bnjmnt4n** [comment]
Looks like the update landed in nixpkgs staging: https://github.com/NixOS/nixpkgs/pull/107324.

**Comment by colemickens** [comment]
This is still an issue, but I'm letting sway and wlroots update by using `wayland` from `nixos-unstable-small`. I'll revert this whenever the update hits `nixos-unstable` (hopefully soon?).

**Comment by berbiche** [comment]
I think this can be closed?

**Comment by Emantor** [comment]
> I think this can be closed?

Yes.
