### ISSUE TITLE
CI job for actual status of master

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#280]
The current  badge is for the update job. We should have another job that just builds master, one to prove it's usually green, and two, to catch when it isn't because the dev pushed on accident.

(my nixup script that I use to keep my development nix repos pushed and up-to-date... it is set to rebase and push and is doing so for nixpkgs-wayland)

**Comment by Artturin** [comment]
https://github.com/nix-community/nixpkgs-wayland/commit/03f164c2a5344768c8186989c30045b7c8c7ebf7
