### ISSUE TITLE
Nix run does not work if the package revision starts with a letter

### ISSUE THREAD

**Issue by berbiche** [nix-community/nixpkgs-wayland#282]
Using `nix run github:colemickens/nixpkgs-wayland#waybar` fails to run because `nix run` extracts the name of the main binary from the derivation name and it doesn't get parsed correctly if the revision does not start with a number
- `builtins.parseDrvName "waybar-a1b2c3d4"` -> `{ name = "waybar-a1b2c3d4"; version = ""; }`
- `builtins.parseDrvName "waybar-1b2c3d4f"` -> `{ name = "waybar"; version = "1b2c3d4f"; }`

I see three solutions:
1. Use the newly introduced `meta.mainProgram` from https://github.com/NixOS/nix/commit/7bd9898d5ca72ed136032590745c56826317a328
2. Update derivation names to the form `name-YYYY-mm-DD-${revision}`
  `builtins.parseDrvName "waybar-2021-03-01-a1b2c3d4"` -> `{ name = "waybar"; ... }`
3. Drop the revision from the name

**Comment by colemickens** [comment]
Hm, trying to understand this...

Where does this requirement stem from, exactly? This is part of how `nix run` fundamentally works? It adds some extra arbitrary restriction on how the referenced package is named?

**Comment by berbiche** [comment]
Extracting the default name of the binary to run from the name of the derivation is how `nix run` works.

And the `meta.mainProgram` would allow the example in the README to work for very recent `nix` versions
