### ISSUE TITLE
xdg-desktop-portal-wlr is pinned

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#283]
Yay, the Sway ecosystem adds a dependency on another C library that isn't packaged right!

`iniparser` doesn't install it's pkg-config file with it's makefile, nor does postInstall take care of it in nixpkgs.

Until then `xdg-desktop-portal-wlr` is pinned.

**Comment by berbiche** [comment]
@colemickens xdg-desktop-portal-wlr can be unpinned and this can be closed I think?
