### ISSUE TITLE
wdisplays (owner on GH) has disappeared

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#287]

**Comment by berbiche** [comment]
@colemickens do you know when wdisplays was last updated?

My fork now points to <https://github.com/MichaelAquilina/wdisplays>, and I don't think this is the new original.

**Comment by berbiche** [comment]
Maybe we could use Emersion's fork? https://github.com/emersion/wdisplays

**Comment by colemickens** [comment]
done: https://github.com/colemickens/nixpkgs-wayland/commit/846f3cecb6f113fee6b855a327a7a104f994d486

**Comment by berbiche** [comment]
@colemickens oops, the "master" branch doesn't have the fix merged in #264.
This one has it <https://github.com/emersion/wdisplays/tree/fix-global-version>.
AUR seems to be using this fork: https://github.com/artizirk/wdisplays

**Comment by colemickens** [comment]
Want to send a PR? :)

**Comment by berbiche** [comment]
Incoming PR

**Comment by Artturin** [comment]
new upstream in https://github.com/nix-community/nixpkgs-wayland/pull/360
