### ISSUE TITLE
project is on-hold

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#293]
As per the rest of my nix projects, I'm pretty much turning my investment to zero until such time that something is done about impure-eval-by-default in stable nix or until actual technical leadership around flakes emerges.

**Comment by Artturin** [comment]
maybe this could be moved to nix-community? i could maintain at least some of the packages if given write access.

**Comment by Artturin** [comment]
https://discourse.nixos.org/t/nix-release-schedule-and-roadmap/14204

**Comment by colemickens** [comment]
Yes, I saw that. It's very exciting! For what it's worth, I'd still been working on this, probably some many hours since I'd originally posted this. :P
