### ISSUE TITLE
sirula is temporarily removed

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#302]
Sirula is removed for now in order to unblock: https://github.com/DorianRudolph/sirula/issues/14

**Comment by colemickens** [comment]
related commit to this repo removing sirula for now: https://github.com/nix-community/nixpkgs-wayland/commit/e94be3d095c60a1b45a2ce72166f6a636f0da121

**Comment by berbiche** [comment]
This can be reverted I think?

**Comment by colemickens** [comment]
Thanks! It already was! https://github.com/nix-community/nixpkgs-wayland/commit/a7447d6e9d66b81d49ce706e52736bc449afa331#diff-6153f194f2a12050ed4a3f6fcca2216325ee1c98921fbda7a187f71ae9e78e2e
