### ISSUE TITLE
request: add wlroots-eglstreams and config to build/cache pkgs built with it

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#305]
see: https://github.com/danvd/wlroots-eglstreams

Seems like we could provide this, a tiny module to enable it via overlay, and then add a job to build and cache it for users.

I can test with a RTX 3080 in a Ryzen machine.

**Comment by colemickens** [comment]
For this to be complete, I think we'd need to have another flakes-compat file for `overlay-egl`, since non-flakes users are just hitting default.nix and directly landing on the overlay output.

It's *tempting* to deprecate `default.nix` and say that we're going to force users to import `overlay.nix` (or `overlay-egl.nix`) and then allow `default.nix` to just map to all flake outputs... but I'm not sure it's worth the hassle and it would spoil the "transparent" seamless feeling that came with adopting flakes in this repo.

**Comment by colemickens** [comment]
This has been partially resolved: https://github.com/nix-community/nixpkgs-wayland/commit/42e07dc73fc569322da41cf980bb103fa8d6880c

These packages are not being cached yet, but I can add that soon.

**Comment by almostnobody** [comment]
[new nvidia beta drivers support gbm](https://www.nvidia.com/download/driverResults.aspx/181167/en?ncid=afm-chs-44270&ranMID=44270&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-9J_Bf_4sVhbKOuwqfhX9qQ&ncid=afm-chs-44270&ranMID=44270&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-GW9klQXQKNxnozXtIsJigA)
> Version: | 495.29.05 BETA
> Release Date: | 2021.10.14

> Added support for the GBM API. This adds the new symlink nvidia-drm_gbm.so pointing to the file libnvidia-allocator.so.VERSION to implement a GBM backend driver usable with the GBM loader from the Mesa project version 21.2 and above, as well as the files libnvidia-egl-gbm.so.1.1.0 and 15_nvidia_gbm.json, which implement EGL support for the GBM platform (EGL_KHR_platform_gbm).

**Comment by colemickens** [comment]
I might instead rip this out since Nvidia 495 + GBM + Sway works pretty decently and is clearly the future.
