### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#309]
As part of the migration, I'm going to close old PRs so I can delete stale branches.

One of those PRs was for aarch64 support.

It should mostly "just work".

For reference, here's that branch: https://github.com/colemickens/nixpkgs-wayland/tree/aarch64

**Comment by Artturin** [comment]
`nix build ".#bundle.aarch64-linux" --system aarch64-linux` builds
