### ISSUE TITLE
wldash is out of date

### ISSUE THREAD

**Issue by tadeokondrak** [nix-community/nixpkgs-wayland#332]
0.3.0 is out: https://github.com/kennylevinsen/wldash/commit/3eb7cddb6c4a3e52950bc500bea2e8fe999c1c0a

**Comment by Artturin** [comment]
No it's not out of date https://github.com/nix-community/nixpkgs-wayland/blob/master/pkgs/wldash/metadata.nix
https://github.com/kennylevinsen/wldash/commit/2538e41f001fa363d3459efe3b8102a354b06dd0

**Comment by tadeokondrak** [comment]
Huh, interesting. I checked a few times recently to see if it's been updated but it looks like something's wrong on my side

**Comment by tadeokondrak** [comment]
Ah, the reason for my confusion was the repository owner change, and the old link doesn't redirect
