### ISSUE TITLE
update.sh: try to automatically catch broken cargo hashes on nixpkgs advance

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#334]
When nixpkgs advances, it can change the way that cargoSha256 is updated. We could catch this in a way or two and attempt to recreate the hash automatically. This would prevent the need for manual intervention that pops up increasingly.

Note, maybe we only package i3status-rust in nixpkgs-wayland that's written in Rust, but it really seems to have issues more than anything else does? (or like compared to zellij/wezterm in my nixcfg which doesn't seem to  break as often?)

**Comment by colemickens** [comment]
A quick hack option would be to:

1. modify the advance workflow
2. on any error:
3. blank out any cargoSha256
4. run ./update.sh in a "force" mode where it always refreshes the cargosha256 if set to zeros

This should (help) ensure we never stay broken from cargo hashes too long.

**Comment by Artturin** [comment]
Hasn't happened since so going to close this
