### ISSUE TITLE
wayfire: fix packaging to be compatible with nixpkgs

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#335]
I tried out wayfire today and noticed that the packaging here is probably not properly overlaid with the derivations from nixpkgs.

Particularly, nixos users are probably use the wrapped wayfireApplications and we sorta stomp all over that.

I'm not sure if there's an easy way to override, we're probably better off copying everything over and figuring out how to accomodate updating multiple sources in a pkg dir.

**Comment by colemickens** [comment]
note: in the meantime I've renamed wayfire to `wayfire-unstable`. In using it day to day I can tell that the overlay is breaking wayfire in certain ways, probably because `wayfire/wayfireApplications` isn't built the same way as sway and doesn't seem to be easily override-able without entirely replacing it.

**Comment by Artturin** [comment]
pinned wayfire in https://github.com/nix-community/nixpkgs-wayland/commit/056310e72b8826a5c1dc098862d183b7a8cdbe13 due to newer revs of it not compiling

**Comment by Artturin** [comment]
Wayfire was dropped in 6b491b27c96a1c653915c194bb9c641160e41a78
