### ISSUE TITLE
wlroots fails to build

### ISSUE THREAD

**Issue by ModdedGamers** [nix-community/nixpkgs-wayland#340]
I'm trying to update my system, and wlroots fails to build with the error
```
cc1: error: /nix/store/mzsb651dndz483j3p3mkdimv6jbipj8a-vulkan-loader-1.3.211.0-dev//nix/store/ricqa5g00rn0rscz2liyiqnhpqgz8kkz-vulkan-headers-1.3.211.0/include: No such file or directory [-Werror=missing-include-dirs]
```
This breaks my entire config and I can't rebuild. What can I do to fix this? It seems to be concatenating 2 paths together(because of the double slash after the word `dev`.

**Comment by Artturin** [comment]
i tested with `nix build ".#wlroots"` and it built for me

send the output of `nixos-version` and

**Comment by ModdedGamers** [comment]
I'm not on nixos. I'm running nix version`nix (Nix) 2.8.0pre20220322_d5d4d98` on arch.

**Comment by Artturin** [comment]
what nixpkgs rev and are you sure its because of this overlay

**Comment by ModdedGamers** [comment]
`e10da1c7f542515b609f8dfbcf788f3d85b14936`

**Comment by bandithedoge** [comment]
I also have the same issue on `22.05.20220417.bd4dffc (Quokka)`.

**Comment by bandithedoge** [comment]
Removing `vulkan-headers` from `buildInputs` produces an error that suggests using `-Dvulkan=disabled` to disable building the Vulkan renderer, but adding it to `mesonFlags` produces another error:

```
meson: error: unrecognized arguments: Dvulkan=disabled
```

**Comment by berbiche** [comment]
I believe this PR in nixpkgs resolves the issue: https://github.com/NixOS/nixpkgs/pull/170748
