### ISSUE TITLE
systemd services removed after update

### ISSUE THREAD

**Issue by djacu** [nix-community/nixpkgs-wayland#346]
**Describe the bug**

I recently updated from e3a2cb54e6fcbe9d92f7c07261e28676c23b2de3 to 81aa488cbe08ab7de90369ac48f2db040aab738d and it causes problems with sway, shutdown and possibly other services. Trying to run sway produces the following errors.

```shell
$ sway
00:00:00.006 [ERROR] [wlr] [libseat] [libseat/backend/logind.c:317] Could not activate session: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [common/terminal.c:162] Could not open target tty: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [seatd/seat.c:61] Could not open tty0 to update VT: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [common/terminal.c:162] Could not open target tty: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [seatd/seat.c:72] Could not open terminal for VT 0: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [seatd/seat.c:461] Could not open VT for client
00:00:00.006 [ERROR] [wlr] [libseat] [common/terminal.c:162] Could not open target tty: Permission denied
00:00:00.006 [ERROR] [wlr] [libseat] [seatd/seat.c:86] Could not open terminal to clean up VT 0: Permission denied
00:00:10.017 [ERROR] [wlr] [backend/backend.c:114] Timeout waiting session to become active
00:00:10.017 [ERROR] [wlr] [backend/backend.c:352] Failed to start a DRM session
00:00:10.018 [ERROR] [sway/server.c:72] Unable to create backend
00:00:10.021 [ERROR] [wlr] [libseat] [common/terminal.c:162] Could not open target tty: Permission denied
00:00:10.021 [ERROR] [wlr] [libseat] [seatd/seat.c:86] Could not open terminal to clean up VT 0: Permission denied
```

The system will not respect a `shutdown` command without `sudo` privileges.

**Expected behavior**

`sway` starts normally and `shutdown` does not require sudo privileges.

**Environment**
 - NixOS-22.11

**Additional context**

While rebuilding I did see the following lines in the tty.

```shell
removing obsolete symlink '/etc/pam.d/polkit-1'...
removing obsolete symlink '/etc/udisks2/udisks2.conf'...
removing obsolete symlink '/etc/pokit-1/rules.d/10-nixos.rules'...
```

I ran `systemctl status polkit.service` and there was no polkit service. Before the update, it was enabled and running.

I did find that adding `security.polkit.enable = true;` to my configuration appears to fix the issue. I've never had to do this before and I'm not sure if I was lucky and should have had it set or if this is unintended behavior.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/186028

```

- The udisks2 service, available at `services.udisks2.enable`, is now disabled by default. It will automatically be enabled through services and desktop environments as needed.
  This also means that polkit will now actually be disabled by default. The default for `security.polkit.enable` was already flipped in the previous release, but udisks2 being enabled by default re-enabled it.
```

the nixos sway module already enables polkit it explicitly https://github.com/NixOS/nixpkgs/blob/600b02324c37abd1280051f872c914113f1f37bf/nixos/modules/programs/sway.nix#L137

**Comment by djacu** [comment]
Ahh I see. I am using the home-manager implementation and submitted an issue there.
https://github.com/nix-community/home-manager/issues/3160
Thanks for the info.
