### ISSUE TITLE
foot: revisit and un-skip

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#352]
Looks like `foot` wants to build a util `xtgettcap` and then use it in its own build.

Maybe just wait until nixpkgs updates and then copy the derivation back? I don't use foot or care enough to babysit another C application.

**Comment by Artturin** [comment]
the skip commit: https://github.com/nix-community/nixpkgs-wayland/commit/d52107c46d6f8b6a9bba4b298755af561a0774dc
