### ISSUE TITLE
[pkg request] ironbar

### ISSUE THREAD

**Issue by pinkcreeper100** [nix-community/nixpkgs-wayland#384]
https://github.com/JakeStanger/ironbar

**Comment by pinkcreeper100** [comment]
oh wait oops they already have nix

**Comment by colemickens** [comment]
whoa! this one wasnt' on my radar.

thank you!

is there an awesome-wayland? I can't keep track of all the new rust+wayland stuff these days!!!

**Comment by pinkcreeper100** [comment]
this one is actively updated
https://github.com/hyprland-community/awesome-hyprland#runners-menus-and-application-launchers
this one is archived
https://github.com/natpen/awesome-wayland
