### ISSUE TITLE
remove wlfreerdp in march 2023

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#386]
Frankly, I'm not sure why I ever had it named differently than the nixpkgs package.

Maybe we can alias it too, just in case.

**Comment by colemickens** [comment]
Is it possible to do aliases with overlays, such that the alias doesn't work for users that have it disabled?

cc: @Artturin maybe you know?

**Comment by colemickens** [comment]
done in: https://github.com/nix-community/nixpkgs-wayland/commit/5ad4d386b919ed3c6490919e03e7134ba2eed4ba

updating this to reflect dropping `wlfreerdp` in March 2023, as the warning indicates

**Comment by FlorianFranzen** [comment]
This breaks `gnome-remote-desktop` for me on unstable, which then breaks the gdm module for me as result:
```
error: builder for '/nix/store/bcy3nz5q71ikci3nr6gn41yr5v1i29ns-gnome-remote-desktop-43.3.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency tss2-tctildr found: YES 3.2.0
       > Library dl found: YES
       > Run-time dependency ffnvcodec found: YES 11.1.5.2
       > Did not find CMake 'cmake'
       > Found CMake: NO
       > Run-time dependency freerdp2 found: NO (tried pkgconfig)
       >
       > meson.build:51:2: ERROR: Dependency "freerdp2" not found, tried pkgconfig
       >
       > A full log can be found at /build/gnome-remote-desktop-43.3/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/bcy3nz5q71ikci3nr6gn41yr5v1i29ns-gnome-remote-desktop-43.3.drv'.
error: 1 dependencies of derivation '/nix/store/zfh0mg9mp71b81gnrglk2757z1318l80-gnome-control-center-43.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gaz2r3zgkvinfprysvc549kfl6ra2hl9-unit-display-manager.service.drv' failed to build
```
It would be great if we could make sure that the overlay `freerdp` provides the same integration as the nixpkgs one, before we overlay them.
