### ISSUE TITLE
some packages are failing due to getting wrong wlroots

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#388]
cc: @Artturin

I'm about 2x as swamped as normal and don't really know when I'm going to be able to look at this.

**Comment by Artturin** [comment]
i pinned cage to the wlroots that nixpkgs uses (rn `wlroots_0_15`) because it was failing. i'll replace the pin with 0_16 because thats what they use in their CI

**Comment by colemickens** [comment]
seems like it broke: https://github.com/nix-community/nixpkgs-wayland/actions/runs/3722727668/jobs/6313786569
