### ISSUE TITLE
support needed: non-flakes, overlay install -> Error: infinite recursion

### ISSUE THREAD

**Issue by ja0nz** [nix-community/nixpkgs-wayland#405]
The process to install nixpkgs-wayland laid out in the REAME (https://github.com/nix-community/nixpkgs-wayland/blob/master/README.md#install-for-nixos-non-flakes-manual-import) is not working anymore.

The error was introduced by commit https://github.com/nix-community/nixpkgs-wayland/commit/cd9623eee03df6505e85d7274d84ac9a7bab025f which changed the overlay.nix file. Need guidance please:)

Error message
```
error: infinite recursion encountered

       at /nix/store/bslnnd9p07ixn6rsx8nwsdvfl490kg3i-nixos/nixos/lib/fixed-points.nix:69:67:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                   ^
           70|
```

**Comment by Artturin** [comment]
https://github.com/nix-community/flake-compat the `{ system ? builtins.currentSystem }:` changes the method of importing our default.nix from just `import x` to `import x {}`

@colemickens

**Comment by Artturin** [comment]
fix in https://github.com/nix-community/nixpkgs-wayland/commit/19019499709f728a33b91686dc4b8bb5fd391b8d

**Comment by ja0nz** [comment]
Super fast🔥 Thanks!
