### ISSUE TITLE
Package request: wl-screenrec

### ISSUE THREAD

**Issue by Mateiadrielrafael** [nix-community/nixpkgs-wayland#407]
[Repo](https://github.com/russelltg/wl-screenrec)

Maybe I should try doing this myself, although I am not familiar with packaging rust apps.

**Comment by colemickens** [comment]
Go for it! I can offer advice if you want, feel free to reply here as much as you want.

I recommend grepping for `buildRustPackage`, copy the derivation, change the meta/src and start fixing up build errors :)

**Comment by colemickens** [comment]
Also, if you don't want to do this, let me know and I'll try to just get it done -- I'm always happy to try a new Rust replacement. I'm curious to compare it to OBS, as well.

**Comment by Mateiadrielrafael** [comment]
> Go for it! I can offer advice if you want, feel free to reply here as much as you want.
> 
> I recommend grepping for `buildRustPackage`, copy the derivation, change the meta/src and start fixing up build errors :)

Thanks, I'll give it a try in a few days!

**Comment by colemickens** [comment]
This has been added to nixpkgs [1], so this should be even more trivial to add here.

[1]: :https://github.com/NixOS/nixpkgs/pull/239462

**Comment by Mateiadrielrafael** [comment]
@colemickens Hi! I personally don't have much of a reason not to use the nixpkgs package directly, so I'll close this for now (feel free to reopen)

**Comment by colemickens** [comment]
This was done in 61f7c9ddbdbfebc134f743b8130714cf1713089d
