### ISSUE TITLE
clipman: being abandonded

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#417]
see: https://github.com/yory8/clipman

It has been archived and currently has this message on its README @ https://github.com/yory8/clipman/tree/8b30de8d3ae29bf88337121cf3bc30afbc2d06c4:

>Github is forcing me to move to 2FA, and I can't be bothered to find out how it's done, nor do I wish to. As I've stopped using a clipboard manager for a while, I have decided to archive this repository rather than move to a decent host. I recommend making your own clone because I'll fully delete my account in the near future.

>Clipman is a finished program: it works, and doesn't need maintenance. It is also very simple and tiny, in fact I should have used python or even just bash. It has some fundamental design flaws that might warrant exploring a redo from scratch, though the big issues still lack a satisfying solution at the wayland protocol level. Any interested party will find abundant documentation about it scattered throughout the issue tracker.

Not sure what to do about this. Probably nothing until it's deleted, and then skip it and/or switch to a fork if one pops up.

**Comment by Artturin** [comment]
the repo was deleted and is blocking update because the src wasn't cached, there seems to be no up to date forks.

**Comment by colemickens** [comment]
:shrug: can't say I'm shocked. oh well. let's just remove it.

**Comment by colemickens** [comment]
https://github.com/nix-community/nixpkgs-wayland/pull/425

**Comment by Artturin** [comment]
I have a clipman binary at the newest version before removal which should work once `patchelf`ed.

http://files.artturin.com/archives/clipman

**Comment by Artturin** [comment]
The nixpkgs package has been updated to a new source https://github.com/NixOS/nixpkgs/commit/4e7d39d716025e9dc3d3af8155a09c875a8d66ca
