### ISSUE TITLE
Newest wl-roots causes hard-crash in Sway

### ISSUE THREAD

**Issue by jboyens** [nix-community/nixpkgs-wayland#444]
Not sure which particular commit is causing the issue but 1ce086a5ec78554848ab094cc135eb6c26839642 is safe for the moment.

Even in `--debug --verbose` I don't get anything and I can't run it under gdb without some effort that escapes me at the moment.

I see:
```
sway[28011]: segfault at 8 ip 00007f7e3d49d485 sp 00007ffeb86a1310 error 4 in libwlroots.so.13[7f7e3d45a000+83000] likely on CPU 6 (core 12, socket 0)
```
appear in my `dmesg` after the crash.

**Comment by Artturin** [comment]
Are you still having the issue, did you report it upstream?
