### ISSUE TITLE
Convert to NUR  repository

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#53]
Per a recent conversation in #nixos, I'm convinced that it makes sense to convert this to a NUR repository. Maybe we could go ahead and add the module here directly too. I'll probably take the chance to rename some packages too (`sway-beta` -> `sway`, `redshift-wayland` -> `redshift`, since these things are in sight and I am already churning a lot here).

cc: @zimbatm for thoughts/input

**Comment by zimbatm** [comment]
no objections here! I don't think we should make any compatibility guarantees at this point or it will hold us back.

**Comment by FlorianFranzen** [comment]
What speaks again merging this repo into upstream nixpkgs? It seems wayland support is on their list of todos anyway: https://github.com/NixOS/nixpkgs/projects/11

**Comment by zimbatm** [comment]
nixpkgs has a policy of not packaging unreleased software. this repo is for the bleeding-edge stuff. eventually all the packages here will get released and can be added to nixpkgs for sure.

**Comment by Artturin** [comment]
Imo this is not relevant anymore
