### ISSUE TITLE
Add wayland session

### ISSUE THREAD

**Issue by suhr** [nix-community/nixpkgs-wayland#61]
Nixpkgs [now supports](https://github.com/NixOS/nixpkgs/issues/32806) wayland sessions, so it's time to provide one for sway.

**Comment by colemickens** [comment]
Sway doesn't support the use of session managers, so I'm not sure it's good to include one. Also, this repo doesn't actually ship any modules currently, though I'm considering it for other cases like this.

If you have one that works reliably, I'd be okay with it, but you'd also have to write up the docs for how to use the module, etc.

**Comment by suhr** [comment]
```
% cat /nix/store/1m010bgfmi4mszwnclsp31xpyl1zlfyb-sway-joined/share/wayland-sessions/sway.desktop                                                                                                                                  ~
[Desktop Entry]
Name=Sway
Comment=SirCmpwn's Wayland window manager
Exec=sway
Type=Application
```

There is an actual `.desktop` file. It is just not available for display managers while it should be.

**Comment by suhr** [comment]
`nixos/modules/services/x11/desktop-managers/gnome3.nix` sets `services.xserver.displayManager.extraSessionFilePackages = [ pkgs.gnome3.gnome-session ];`, probably the same trick would work for sway.

Blocking issue: https://github.com/NixOS/nixpkgs/issues/53277

**Comment by colemickens** [comment]
Interesting, thanks for the tip.

If/when I add a sway module here, I'll do as you suggest. In the meantime, you might also suggest this change on the NixOS/nixpkgs repository where the sway module lives now.

**Comment by Artturin** [comment]
Maintaining the module upstream makes more sense
